# Перевёл: serj1983 (post.serj@gmail.com)

translate russian strings:

    old "End Turn"
    new "Завершить ход"
    old "End your turn and retain up to 2 stamina"
    new "Завершите свой ход и сохраните до 2 единиц выносливости"
    old "Save up to 2 Stamina to use next turn."
    new "Сохраните до 2 единиц выносливости, чтобы использовать их в следующием ходу."
    old "Turtle"
    new "Черепаха"
    old "End turn and set stance to Defensive"
    new "Завершите ход и примите оборонительную стойку"
    old "+1 Guard"
    new "+1 Защита"
    old "Body Hook"
    new ""
    old "+20% Damage to next attack this turn"
    new "+20% урона к следующей атаке в этот ход"
    old "Jab"
    new "Джеб"
    old "Attack with a quick jab straight to the chin."
    new "Атакуйте быстрым джебом прямо в подбородок."
    old "Next Attack this turn ignores guard"
    new "Следующая атака в этот ход игнорирует защиту"
    old "Hook"
    new "Хук"
    old "A devastating attack to your opponent's head."
    new "Сокрушительная атака в голову вашего противника."
    old "Opp has -2 Stamina at the start of their next turn if not blocked [[Once per turn]]"
    new "У противника есть -2 выносливости в начале следующего хода, если он не заблокирует [[Once per turn]]"
    old "Kick"
    new "Удар"
    old "A devastating attack to your opponent's body."
    new "Сокрушительная атака по телу противника."
    old "+20% Damage if used with exactly 5 Stamina left"
    new "+20% урона, если используется, когда осталось ровно 5 единиц выносливости"
    old "Headbutt"
    new "Удар головой"
    old "If you used \"Turtle\" last turn, deal +30% more Damage"
    new "Если вы использовали \"Черепаху\" в прошлом ходу, то нанесёте на +30% больше урона."
    old "Overhand Punch"
    new "Удар с разворота"
    old "Breaks Guard and deals 100% Damage if it's at 30% or less"
    new "Разбивает защиту и наносит 100% урона, если она находится на уровне 30% или ниже"
    old "Uppercut"
    new "Апперкот"
    old "If Opponents's Will is 20% or less, this attack deals +50% Damage"
    new "Если воля противника составляет 20% или меньше, эта атака наносит +50% урона."
    old "Sucker Punch"
    new "Удар исподтишка"
    old "50% Damage bypasses Guard"
    new "50% урона обходит защиту"
